version: '3'

services:
  doc:
    image: gifmagazine/aglio-drakov
    restart: always
    ports:
      - "3000:3000"
    working_dir: /projects
    volumes:
      - "../md:/projects"
    tty: true
    command: aglio --theme-variables slate -i includes.txt -s -h 0.0.0.0 & drakov --config config.js
  mock:
    image: gifmagazine/aglio-drakov
    restart: always
    ports:
      - "80:80"
    working_dir: /projects
    volumes:
      - "../md:/projects"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    tty: true
    command: sh -c "nginx; drakov -f "**/*.md" --watch --discover --public --debugMode -p 3001"